INSERT INTO `Resource`
    (`id`,`name`,`description`)
VALUES
    ('1','Corn','corn'),
    ('2','Eggs','eggs'),
    ('3','Chickens','chickens'),
    ('4','Dung','dung'),
    ('5','Chickens','chickens'),
    ('6','Cocks','cocks'),
    ('7','Fighting Cocks','fighting cocks'),
    ('8','Stone',' stone'),
    ('9','Cocks with hammers','cocks with hammers'),
    ('10','Cocks with slingshots','cocks with throwers (rogatki)'),
    ('11','Steel','steel'),
    ('12','Cocks swordsmen (in lats)','cocks swordsmen (in lats)'),
    ('13','Cocks with axes (in lats)','cocks with axes (in lats)'),
    ('14','Wood',' wood'),
    ('15','Cocks archers','cocks archers'),
    ('16','Cocks lancers','cocks lancers'),
    ('17','Gunpowder','gunpowder'),
    ('18','Cocks gunners','cocks gunners'),
    ('19','cocks with bazookas','cocks with bazookas'),
    ('20','Mana','mana'),
    ('21','Cocks magicians"','cocks magicians'),
    ('22','Cocks prophets','cocks prophets'),
    ('23','XP','experience'),
    ('24','Cockiness',' "cockiness"');