INSERT INTO `Building`
    (`id`, `name`,`description`)
VALUES
    (1,'Granary','Granary ---> corn'),
    (2,'Chicken House','Chicken House ---> eggs'),
    (3,'Incubator','Incubator ---> chickens'),
    (4,'Cleaning Center','Cleaning Center ---> dung'),
    (5,'Chicken Yard','Chicken Yard ---> hens'),
    (6,'Cocks House','Cocks House ---> cocks'),
    (7,'Cocks Barrack','Cocks Barrack ---> fighting cocks'),
    (8,'Quarry','Quarry ---> stone'),
    (9,'School of Hammers','School of Hammers ---> cocks with hammers'),
    (10,'School of Slingshots','School of Slingshots ---> cocks with slingshots'),
    (11,'Blast Furnace','Blast Furnace ---> steel'),
    (12,'School of Swordsmens','School of Swordsmens ---> cocks swordsmen (in lats)'),
    (13,'School of Axes','School of Axes ---> cocks with axes (in lats)'),
    (14,'Logger','Logger ---> wood'),
    (15,'School of Archers','School of Archers ---> "cocks archers"'),
    (16,'School of Lancers','School of Lancers ---> cocks lancers'),
    (17,'Alchemy Laboratory','Alchemy Laboratory ---> gunpowder'),
    (18,'School of Gunners','School of Gunners ---> cocks gunners'),
    (19,'School of Bazookas','School of Bazookas ---> cocks with bazookas'),
    (20,'Altar','Altar ---> mana'),
    (21,'School of Mages','School of Mages ---> cocks magicians'),
    (22,'Ziggurat','Ziggurat ---> cocks prophets');