INSERT INTO `Building`
    (`id`, `name`,`description`)
VALUES
    ('1','Granary','ambar ---> zerno'),
    ('2','Chicken_House','kuriatnik ---> eggs'),
    ('3','Incubator','incubator ---> tsipliata'),
    ('4','Cleaning_Center','cleaning center ---> pomet'),
    ('5','Chicken_Yard','chicken yard ---> chickens'),
    ('6','Cock_House','cock house ---> cocks'),
    ('7','Cock_Barrack','cock barracks ---> fighting cocks'),
    ('8','Quarry','kamenolomnia ---> stone'),
    ('9','Hammer-Stonecutter','moloto-kamenotes ---> cocks with hammers'),
    ('10','Throwing_School','metanie ---> cocks with throwers (rogatki)'),
    ('11','Blast_furnace','domennaya pech ---> steel'),
    ('12','Smithy','kuznitsa ---> cocks with swords (in armor)'),
    ('13','Axe_school','axe school ---> cocks with axes (in armor)'),
    ('14','Wood_logger','lesorubka ---> wood'),
    ('15','Carpentry','plotnitskaya ---> archer cocks'),
    ('16','Joinery','stoliarka ---> cocks with pikes'),
    ('17','Alchemical_Lab','Alchemical_Lab ---> gunpowder'),
    ('18','Armory','armory weapon ---> cocks with guns'),
    ('19','Ballistic_Base','ballistic base ---> cocks with bazooka'),
    ('20','Sanctuary','altar ---> mana'),
    ('21','Magic_School','school of magic ---> cocks-wizards'),
    ('22','Ziggurat','zikkurat ---> seer cocks (providtsy)');