INSERT INTO `Upgrade`
    (`id`, `name`,`description`)
VALUES
    ('1','Upgrade granary','Granary ---> corn Upgrade'),
    ('2','Upgrade granary and chikens house','Granary and chikens house ---> corn and eggs Upgrade'),
    ('3','Initialize the chikens','Incubator ---> chikens Upgrade'),
    ('4','F@ck this, i am out','Cleaning center ---> dung Upgrade'),
    ('5','Glue a hens','Chicken yard ---> hens Upgrade'),
    ('6','Ruffle up a cocks','Cocks house ---> cocks Upgrade'),
    ('7','Mother-in-law? I am in the army','Cocks barracks ---> fighting cocks Upgrade'),
    ('8','Minecraft?','Quarry ---> stone Upgrade'),
    ('9','USSC','School of Hammers ---> cocks with hammers Upgrade'),
    ('10','Sling? Nooooo','School of Slingshots ---> cocks with slingshots Upgrade'),
    ('11','Steelworkers','Blast furnace ---> steel Upgrade'),
    ('12','Chicken infantry','School of Swordsmens ---> cocks swordsmen (in lats) Upgrade'),
    ('13','Clumsy fame','School of Axes ---> cocks with axes (in lats) Upgrade'),
    ('14','New saws','Logger ---> wood Upgrade'),
    ('15','Add optical sight to all bow','School of Archers ---> cocks archers Upgrade'),
    ('16','Training of lancers','School of Lancers ---> cocks lancers Upgrade'),
    ('17','Crazy professor','Alchemy Laboratory ---> gunpowder Upgrade'),
    ('18','Add fire transfer pen','School of Gunners ---> cocks gunners Upgrade'),
    ('19','ChiRambo','ballistic base ---> School of Bazookas ---> cocks with bazookas Upgrade'),
    ('20','Meditation','Altar ---> mana Upgrade'),
    ('21','Kill the Witcher','School of Mages ---> cocks magicians Upgrade'),
    ('22','Life for Ner Zul','Ziggurat ---> cocks prophets Upgrade'),
    ('23','Pesticides','Granary ---> corn Upgrade Upgrade'),
    ('24','Broiler','Chikens house and Incubator and Chicken yard ---> eggs and chikens and hens Upgrade'),
    ('25','Red bull','Cocks house and barracks ---> cocks and fighting cocks Upgradee'),
    ('26','Muscle gym','School of Hammers and Slingshots ---> cocks with hammers and slingshots Upgrade'),
    ('27','New armor','School of Swordsmens and Axes ---> cocks swordsmen and axes (in lats) Upgrade'),
    ('28','Steel feathers','School of Archers and Lancers ---> cocks archers and lancers Upgrade'),
    ('29','Armed and dangerous','School of Gunners and Bazookas ---> cocks gunners and bazookas Upgrade'),
    ('30','Disney Princess? Really?','School of Mages and Ziggurat ---> cocks magicians and prophets Upgrade');
