INSERT INTO `Resource`
    (`id`,`name`,`description`)
VALUES
    ('1','Corn','corn'),
    ('2','Eggs','eggs'),
    ('3','Chick','chick(tsiplionok)'),
    ('4','Cockshit',' cockshit'),
    ('5','Chickens','chickens'),
    ('6','Cocks','cocks'),
    ('7','Fighting_Cocks','fighting cocks'),
    ('8','Stone',' stone'),
    ('9','Hammer_Cocks',' cocks with hammers'),
    ('10','Throwing_Cocks',' cocks with throwers (rogatki)'),
    ('11','Steel','steel'),
    ('12','Sworded_Cocks',' cocks with swords (in armor)'),
    ('13','Axed_Cocks',' cocks with axes (in armor)'),
    ('14','Wood',' wood'),
    ('15','Archers',' archer cocks'),
    ('16','Spear','cocks with spears (piki)'),
    ('17','Gunpowder','gunpowder'),
    ('18','Guns',' cocks with guns'),
    ('19','Bazookas',' cocks with bazooka'),
    ('20','Magic',' magic'),
    ('21','Wizards',' cocks-wizards'),
    ('22','Prophet',' cock-prophet'),
    ('23','XP',' Experience'),
    ('24','Power',' king power');