INSERT INTO `Card`
    (`name`,`description`)
VALUES
    ('1','Granary','Granary ---> corn'),
    ('2','Chicken House','Chicken House ---> eggs'),
    ('3','Incubator','Incubator ---> chickens'),
    ('4','Cleaning Center','Cleaning Center ---> dung'),
    ('5','Chicken Yard','Chicken Yard ---> hens'),
    ('6','Cocks House','Cocks House ---> cocks'),
    ('7','Cocks Barrack','Cocks Barrack ---> fighting cocks'),
    ('8','Quarry','Quarry ---> stone'),
    ('9','School of Hammers','School of Hammers ---> cocks with hammers'),
    ('10','School of Slingshots','School of Slingshots ---> cocks with slingshots'),
    ('11','Blast Furnace','Blast Furnace ---> steel'),
    ('12','School of Swordsmens','School of Swordsmens ---> cocks swordsmen (in lats)'),
    ('13','School of Axes','School of Axes ---> cocks with axes (in lats)'),
    ('14','Logger','Logger ---> wood'),
    ('15','School of Archers','School of Archers ---> "cocks archers"'),
    ('16','School of Lancers','School of Lancers ---> cocks lancers'),
    ('17','Alchemy Laboratory','Alchemy Laboratory ---> gunpowder'),
    ('18','School of Gunners','School of Gunners ---> cocks gunners'),
    ('19','School of Bazookas','School of Bazookas ---> cocks with bazookas'),
    ('20','Altar','Altar ---> mana'),
    ('21','School of Mages','School of Mages ---> cocks magicians'),
    ('22','Ziggurat','Ziggurat ---> cocks prophets'),
    ('23','Upgrade granary','Granary ---> corn Upgrade'),
    ('24','Upgrade granary and chikens house','Granary and chikens house ---> corn and eggs Upgrade'),
    ('25','Initialize the chikens','Incubator ---> chikens Upgrade'),
    ('26','F@ck this, i am out','Cleaning center ---> dung Upgrade'),
    ('27','Glue a hens','Chicken yard ---> hens Upgrade'),
    ('28','Ruffle up a cocks','Cocks house ---> cocks Upgrade'),
    ('29','Mother-in-law? I am in the army','Cocks barracks ---> fighting cocks Upgrade'),
    ('30','Minecraft?','Quarry ---> stone Upgrade'),
    ('31','USSC','School of Hammers ---> cocks with hammers Upgrade'),
    ('32','Sling? Nooooo','School of Slingshots ---> cocks with slingshots Upgrade'),
    ('33','Steelworkers','Blast furnace ---> steel Upgrade'),
    ('34','Chicken infantry','School of Swordsmens ---> cocks swordsmen (in lats) Upgrade'),
    ('35','Clumsy fame','School of Axes ---> cocks with axes (in lats) Upgrade'),
    ('36','New saws','Logger ---> wood Upgrade'),
    ('37','Add optical sight to all bow','School of Archers ---> cocks archers Upgrade'),
    ('38','Training of lancers','School of Lancers ---> cocks lancers Upgrade'),
    ('39','Crazy professor','Alchemy Laboratory ---> gunpowder Upgrade'),
    ('40','Add fire transfer pen','School of Gunners ---> cocks gunners Upgrade'),
    ('41','ChiRambo','ballistic base ---> School of Bazookas ---> cocks with bazookas Upgrade'),
    ('42','Meditation','Altar ---> mana Upgrade'),
    ('43','Kill the Witcher','School of Mages ---> cocks magicians Upgrade'),
    ('44','Life for Ner Zul','Ziggurat ---> cocks prophets Upgrade'),
    ('45','Pesticides','Granary ---> corn Upgrade Upgrade'),
    ('46','Broiler','Chikens house and Incubator and Chicken yard ---> eggs and chikens and hens Upgrade'),
    ('47','Red bull','Cocks house and barracks ---> cocks and fighting cocks Upgradee'),
    ('48','Muscle gym','School of Hammers and Slingshots ---> cocks with hammers and slingshots Upgrade'),
    ('49','New armor','School of Swordsmens and Axes ---> cocks swordsmen and axes (in lats) Upgrade'),
    ('50','Steel feathers','School of Archers and Lancers ---> cocks archers and lancers Upgrade'),
    ('51','Armed and dangerous','School of Gunners and Bazookas ---> cocks gunners and bazookas Upgrade'),
    ('52','Disney Princess? Really?','School of Mages and Ziggurat ---> cocks magicians and prophets Upgrade');


