INSERT INTO `Upgrade`
    (`id`, `name`,`description`)
VALUES
    ('1','Granary_Upgrade','ambar ---> zerno_Upgrade'),
    ('2','Chicken_House_Upgrade','kuriatnik ---> eggs_Upgrade'),
    ('3','Incubator_Upgrade','incubator ---> tsipliata_Upgrade'),
    ('4','Cleaning_Center_Upgrade','cleaning center ---> pomet_Upgrade'),
    ('5','Chicken_Yard_Upgrade','chicken yard ---> chickens_Upgrade'),
    ('6','Cock_House_Upgrade','cock house ---> cocks_Upgrade'),
    ('7','Cock_Barrack_Upgrade','cock barracks ---> fighting cocks_Upgrade'),
    ('8','Quarry_Upgrade','kamenolomnia ---> stone_Upgrade'),
    ('9','Hammer_Stonecutter_Upgrade','moloto-kamenotes ---> cocks with hammers_Upgrade'),
    ('10','Throwing_School_Upgrade','metanie ---> cocks with throwers (rogatki)_Upgrade'),
    ('11','Blast_furnace_Upgrade','domennaya pech ---> steel_Upgrade'),
    ('12','Smithy_Upgrade','kuznitsa ---> cocks with swords (in armor)_Upgrade'),
    ('13','Axe_school_Upgrade','axe school ---> cocks with axes (in armor)_Upgrade'),
    ('14','Wood_logger_Upgrade','lesorubka ---> wood_Upgrade'),
    ('15','Carpentry_Upgrade','plotnitskaya ---> archer cocks_Upgrade'),
    ('16','Joinery_Upgrade','stoliarka ---> cocks with pikes_Upgrade'),
    ('17','Alchemical_Lab_Upgrade','Alchemical_Lab ---> gunpowder_Upgrade'),
    ('18','Armory_Upgrade','armory weapon ---> cocks with guns_Upgrade'),
    ('19','Ballistic_Base_Upgrade','ballistic base ---> cocks with bazooka_Upgrade'),
    ('20','Sanctuary_Upgrade','altar ---> mana_Upgrade'),
    ('21','Magic_School_Upgrade','school of magic ---> cocks-wizards_Upgrade'),
    ('22','Ziggurat_Upgrade','zikkurat ---> seer cocks (providtsy)_Upgrade');