INSERT INTO `Upgrade`
    (`id`, `name`,`description`)
VALUES
    ('1','Granary_Upgrade','corn ---> corn_Upgrade'),
    ('2','Chicken_House_Upgrade','chicken house ---> eggs_Upgrade'),
    ('3','Incubator_Upgrade','incubator ---> tsipliata_Upgrade'),
    ('4','Cleaning_Center_Upgrade','cleaning center ---> cockshit_Upgrade'),
    ('5','Chicken_Yard_Upgrade','chicken yard ---> chickens_Upgrade'),
    ('6','Cock_House_Upgrade','cock house ---> cocks_Upgrade'),
    ('7','Cock_Barrack_Upgrade','cock barracks ---> fighting cocks_Upgrade'),
    ('8','Quarry_Upgrade','stone pit ---> stone_Upgrade'),
    ('9','Hammer_Stonemason_Upgrade','stonemason with a hammer ---> cocks with hammers_Upgrade'),
    ('10','Throwing_School_Upgrade','Throwing ---> cocks with throwers (rogatki)_Upgrade'),
    ('11','Blast_furnace_Upgrade','blast furnace ---> steel_Upgrade'),
    ('12','Smithy_Upgrade','kuznitsa ---> cocks with swords (in armor)_Upgrade'),
    ('13','Axe_school_Upgrade','axe school ---> cocks with axes (in armor)_Upgrade'),
    ('14','Wood_logger_Upgrade','sawmill ---> wood_Upgrade'),
    ('15','Carpentry_Upgrade','carpentry ---> archer cocks_Upgrade'),
    ('16','Joinery_Upgrade','spears factory ---> cocks with spear_Upgrade'),
    ('17','Alchemical_Lab_Upgrade','Alchemical_Lab ---> gunpowder_Upgrade'),
    ('18','Armory_Upgrade','armory weapon ---> cocks with guns_Upgrade'),
    ('19','Ballistic_Base_Upgrade','ballistic base ---> cocks with bazooka_Upgrade'),
    ('20','Sanctuary_Upgrade','altar ---> mana_Upgrade'),
    ('21','Magic_School_Upgrade','school of magic ---> cocks-wizards_Upgrade'),
    ('22','Ziggurat_Upgrade','ziggurat ---> seer cocks (providtsy)_Upgrade');